//
//  UIResources.swift
//  UIResources
//
//  Created by tmp on 19/02/2026.
//

import Foundation

// MARK: this is generated by SwiftGen:


/// `ChromaticIcons` have enabled setting "renderingMode: alwaysTemplate" in assets file, so
/// you don't need to write `image.renderingMode(.template)` in code
public enum ChromaticIcons {
    internal static let assetBundlePath: String = currentBundle.path(forResource: "ChromaticIconsBundle", ofType: "bundle")!
    internal static let assetBundle: Bundle = Bundle(path: assetBundlePath)!
    
    public static let addCircleBoldStreamlineUltimate = ImageAsset(name: "Add-Circle-Bold--Streamline-Ultimate", bundle: assetBundle).image
    public static let sms = ImageAsset(name: "SMS", bundle: assetBundle).image
    
    public enum SwiftUI {
        public static let sms = ImageAsset(name: "SMS", bundle: assetBundle).swiftUIImage
    }
}


#if os(OSX)
  public import AppKit.NSImage
  public typealias AssetColorTypeAlias = NSColor
  public typealias AssetImageTypeAlias = NSImage
#elseif os(iOS) || os(tvOS) || os(watchOS)
  public import UIKit.UIImage
  public typealias AssetColorTypeAlias = UIColor
  public typealias AssetImageTypeAlias = UIImage
#endif

import SwiftUI

public struct ImageAsset {
  public let name: String
  public let bundle: Bundle

  public var image: AssetImageTypeAlias {
    #if os(iOS) || os(tvOS)
    let image = AssetImageTypeAlias(named: name, in: bundle, compatibleWith: nil)
    #elseif os(OSX)
    let image = bundle.image(forResource: NSImage.Name(name))
    #elseif os(watchOS)
    let image = AssetImageTypeAlias(named: name)
    #endif
    guard let result = image else { fatalError("Unable to load image named \(name).") }
    return result
  }

  public var swiftUIImage: Image { Image(name, bundle: bundle) }
}

public extension AssetImageTypeAlias {
  @available(OSX, deprecated,
    message: "This initializer is unsafe on macOS, please use the ImageAsset.image property")
  convenience init!(asset: ImageAsset) {
    #if os(iOS) || os(tvOS)
    let bundle = asset.bundle
    self.init(named: asset.name, in: bundle, compatibleWith: nil)
    #elseif os(OSX)
    self.init(named: NSImage.Name(asset.name))
    #elseif os(watchOS)
    self.init(named: asset.name)
    #endif
  }
}

fileprivate let currentBundle = Bundle(for: BundleToken.self)

private final class BundleToken {}

@available(iOS 17.0, *)
extension ImageResource {
    public static let lock5 = ImageResource(name: "Lock5", bundle: ChromaticIcons.assetBundle)
}
